---

- name: Apply the provided configuration demo email notification
  hosts: R
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Config hostname
      cisco.ios.ios_hostname:
        config:
          hostname: R
        state: merged
      register: print_output
  
