name: Run Ansible Playbook

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible paramiko
        ansible-galaxy collection install cisco.ios

    - name: Run Ansible playbook
      run: |
        # Your existing Ansible playbook command
        ansible-playbook -i hosts hostname.yml

  notify_discord:
    runs-on: ubuntu-latest

    needs: deploy
    if: always()
    steps:
      - name: Send Discord Notification
        run: |
          commit_sha="${{ github.sha }}"
          commit_url="https://github.com/${{ github.repository }}/commit/${commit_sha}"
          echo "GitHub Actions Build Status: ${{ needs.deploy.status }}"
          echo "GitHub Actions Build Conclusion: ${{ needs.deploy.conclusion }}"
          echo "Commit URL: $commit_url"
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"content\": \"GitHub Actions Build Is Trigger: ${{ needs.deploy.status }}\nCommit URL: [${commit_sha}](${commit_url})\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
