name: Run Ansible Playbook

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible paramiko
        ansible-galaxy collection install cisco.ios
    - name: Run Ansible playbook
      run: ansible-playbook -i hosts hostname.yml
      env:
        ANSIBLE_CONFIG: ./ansible.cfg

  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Notification
        if: always()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "GitHub Actions Build Success!"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
