name: Run Ansible Playbook

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    outputs:
      step1Result: ${{ steps.deploy.outputs.result }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible paramiko
        ansible-galaxy collection install cisco.ios

    - name: Run Ansible playbook
      id: deploy
      run: |
        # Your existing Ansible playbook command
        ansible-playbook -i hosts hostname.yml
        echo "::set-output name=result::success"  # Set an output variable

    - name: Upload deploy result
      uses: actions/upload-artifact@v2
      with:
        name: deploy-result
        path: ${{ github.workspace }}

  notify-discord:
    runs-on: ubuntu-latest

    needs: deploy

    steps:
      - name: Download deploy result
        uses: actions/download-artifact@v2
        with:
          name: deploy-result
          path: ${{ github.workspace }}

      - name: Send Discord Notification
        if: always()
        run: |
          result=$(cat ${{ github.workspace }}/result.txt)
          if [ "$result" == "success" ]; then
            echo "GitHub Actions Build Success!"
            curl -X POST -H "Content-Type: application/json" \
              -d '{"content": "GitHub Actions Build Success!"}' \
              ${{ secrets.DISCORD_WEBHOOK_URL }}
          else
            echo "GitHub Actions Build Failed!"
          fi
