name: Run Ansible Playbook

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    outputs:
      step1Result: ${{ steps.deploy.outputs.result }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible paramiko
        ansible-galaxy collection install cisco.ios

    - name: Run Ansible playbook
      id: deploy
      run: |
        # Your existing Ansible playbook command
        ansible-playbook -i hosts hostname.yml

  job-B:
    runs-on: ubuntu-latest

    needs: deploy
    if: ${{ needs.job-A.result == 'failure' }}

    steps:
      - name: Send Discord Notification
        run: |
          echo "GitHub Actions Build Failed!"
          curl -X POST -H "Content-Type: application/json" \
            -d '{"content": "GitHub Actions Build Failed!"}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
